config/routes.rb
Rails.application.routes.draw do
  # root "suggestions#index"
  root to: 'application#angular'

  post 'authenticate' => 'auth#authenticate'

  resources :users

  # resource :session, only: [:new, :create]
  # resources :sessions, only: [:destroy]

  resources :suggestions, except: [:new] do
    resources :votes, only: [:create]
    resources :comments, only: [:show, :create]
  end

  resources :comments, only: [:show] do
    resources :votes, only: [:create]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :suggestion, :body, :author, presence: true

  belongs_to :suggestion
  belongs_to :author, class_name: "User", foreign_key: "user_id"

  has_many :votes, as: :voteable, dependent: :destroy

  def vote_count
    upvotes = self.votes.where(upvote: true).length
    downvotes = self.votes.length - upvotes

    upvotes - downvotes
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login!

  def create
    suggestion = Suggestion.find(params[:suggestion_id])
    comment = suggestion.comments.new(comment_params)
    comment.author = User.all.first
    comment.save

    respond_with(comment)
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :suggestion_id)
  end
end

app/views/comments/_form.html.erb
<form class="" action="<%= comments_url %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="comment[suggestion_id]" value="<%= suggestion.id %>">
  <label for="comment_body"><h4>Add Comment</h4></label>
  <textarea id="comment_body" name="comment[body]"></textarea>
  <br>
  <input type="submit" value="submit">
</form>