config/routes.rb
Rails.application.routes.draw do
  # root "suggestions#index"
  root to: 'application#angular'

  post 'authenticate' => 'auth#authenticate'

  resources :users

  # resource :session, only: [:new, :create]
  # resources :sessions, only: [:destroy]

  resources :suggestions, except: [:new] do
    resources :votes, only: [:create]
    resources :comments, only: [:show, :create]
  end

  resources :comments, only: [:show] do
    resources :votes, only: [:create]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :password_digest, presence: { message: "Password can't be blank"}

  attr_reader :password

  has_many :sessions, dependent: :destroy
  has_many :suggestions, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)

    !user.nil? && user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password_digest
    BCrypt::Password.new(super)
  end

  def is_owner?(type, item)
    self.send("#{type}s").include?(item)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_no_login!, only: [:create]
  # before_action :require_is_current_user, only: [:edit, :update]

  def create
    user = User.new(user_params)

    if user.save
      respond_with user
    else
      render json: { errors: user.errors.full_messages }, status: :conflict
    end

    # if @user.save
    #   login_user!(@user)
    #   redirect_to user_url(@user)
    # else
    #   add_flash_error(@user.errors.full_messages)
    #   redirect_to root_url
    # end
  end

  def show
    @user = User.includes(:suggestions).find(params[:id])
    @suggestions = @user.suggestions

    render :show
  end

  def edit
    @user = User.find(params[:id])

    render :edit
  end

  def update
    @user = User.find(params[:id])
    current_password = user_params["current_password"]
    @new_password = user_params["password"]

    if !@user.is_password?(current_password)
      handle_incorrect_password
    else
      edit_user
      attempt_save_after_edit
    end
  end

  private
  def require_is_current_user
    current_user == User.find(params[:id])
  end

  def handle_incorrect_password
    add_flash_error("Current Password is Incorrect")
    redirect_to edit_user_url(@user)
  end

  def edit_user
    changes = { username: user_params["username"] }
    changes[:password] = @new_password unless @new_password.empty?
    @user.assign_attributes(changes)
  end

  def attempt_save_after_edit
    if @user.save
      redirect_to user_url(@user)
    else
      add_flash_error(@user.errors.full_messages)
      redirect_to edit_user_url(@user)
    end
  end
end

app/views/users/edit.html.erb
<h1>Edit User</h1>

<% action = user_url(@user) %>
<form class="" action="<%= action %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="PATCH">

  <label for="user_username">Username</label>
  <input id="user_username" name="user[username]" type="text" value="<%= @user.username %>">
  <br>

  <label for="user_new_password">Change Password</label>
  <input id="user_new_password" name="user[password]" type="password">
  <br>

  <label for="user_old_password">Enter Current Password to Make Changes</label>
  <input id="user_old_password" name="user[current_password]" type="password">
  <br>

  <input type="submit" value="submit">
</form>

app/views/users/index.html.erb
<% @users.each do |u| %>
  <p><%= u.username %></p>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render "shared/signin", action: users_url %>

app/views/users/show.html.erb
<h3><%= @user.username %></h3>
<h4>Suggestions:</h4>
<% @suggestions.each do |suggestion| %>
  <%= link_to suggestion.title, suggestion_url(suggestion) %>
  <br>
<% end %>
<br>
<%= link_to "Edit", edit_user_url(@user) %>
<br>
<%= link_to "Home", root_url %>