config/routes.rb
Rails.application.routes.draw do
  # root "suggestions#index"
  root to: 'application#angular'

  post 'authenticate' => 'auth#authenticate'

  resources :users

  # resource :session, only: [:new, :create]
  # resources :sessions, only: [:destroy]

  resources :suggestions, except: [:new] do
    resources :votes, only: [:create]
    resources :comments, only: [:show, :create]
  end

  resources :comments, only: [:show] do
    resources :votes, only: [:create]
  end
end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
  validates :author, presence: true

  validates :title, presence: true

  belongs_to :author, class_name: "User", foreign_key: :user_id

  has_many :comments, dependent: :destroy
  has_many :votes, as: :voteable, dependent: :destroy

  def vote_count
    upvotes = self.votes.where(upvote: true).length
    downvotes = self.votes.length - upvotes

    upvotes - downvotes
  end

  def author_username
    self.author.username
  end
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  before_action :require_login!, only: [:create, :new]
  before_action :require_current_user_is_owner!, only: [:update, :edit, :destroy]

  def index
    @suggestions = Suggestion.includes(:author, :votes, :comments).all

    respond_with :index
  end

  def show
    @suggestion = Suggestion.includes(:author, :votes, :comments => [:author]).find(params[:id])

    respond_with :show
  end

  def create
    @suggestion = Suggestion.new(suggestion_params)

    @suggestion.author = current_user
    @suggestion.save

    respond_with :create
  end

  def update
    suggestion = Suggestion.find(params[:id])
    suggestion.update_attributes(suggestion_params)

    respond_with suggestion
  end

  def destroy
    suggestion = Suggestion.find(params[:id])
    suggestion.destroy

    respond_with suggestion
  end

  def current_user_is_owner?
    current_user.is_owner?(:suggestion, Suggestion.find(params[:id]))
  end

  private
  def suggestion_params
    params.require(:suggestion).permit(:title, :body)
  end


end

app/views/suggestions/_comments_votes.html.erb
<p><strong>Comments</strong> ( <%= suggestion.comments.length %> ) |
  <strong>Score</strong> <%= suggestion.vote_count %></p>

app/views/suggestions/_form.html.erb
<% action = suggestion.persisted? ? suggestion_url(suggestion) : suggestions_url %>

<form class="" action="<%= action %>" method="post">
  <%= auth_token %>

  <% if suggestion.persisted? %>
    <% submit_text = "Update Suggestion" %>
    <input type="hidden" name="_method" value="PATCH">
  <% else %>
    <% submit_text = "Create Suggestion" %>
  <% end %>

  <label for="suggestion_title">Title</label>
  <input type="text" name="suggestion[title]" value="<%= suggestion.title %>">
  <br>
  <label for="suggestion_body">Body</label>
  <textarea name="suggestion[body]"><%= suggestion.body %></textarea>
  <br>
  <input type="submit" value="<%= submit_text %>">
</form>

app/views/suggestions/edit.html.erb
<h1>Edit Suggestion</h1>
<%= render "shared/errors" %>
<%= render "form", suggestion: @suggestion %>

app/views/suggestions/index.html.erb
<% @suggestions.each do |suggestion| %>
  <h3><%= link_to suggestion.title, suggestion_url(suggestion) %></h3>
  <p><%= suggestion.body %></p>
  <%= render "comments_votes", suggestion: suggestion %>
<% end %>
<% if logged_in? %>
<%= link_to "Make a suggestion", new_suggestion_url %>
<% end %>

app/views/suggestions/new.html.erb
<h1>Create Suggestion</h1>
<%= render "shared/errors" %>
<%= render "form", suggestion: @suggestion %>

app/views/suggestions/show.html.erb
<h2><%= @suggestion.title %></h2>
<% if logged_in? && current_user_is_owner? %>
<%= link_to "Edit", edit_suggestion_url(@suggestion) %>
<%= link_to "Delete", @suggestion, method: :delete %>
<% end %>
<h3>by <%= link_to @author.username, user_url(@author) %></h3>
<p><%= @suggestion.body %></p>
<%= render "comments_votes", suggestion: @suggestion %>
<% @comments.each_with_index do |comment, idx| %>
  <p><%= idx + 1 %>. <%= comment.body %></p>
  <h5>by <%= comment.author.username %></h5>
<% end %>
<% if logged_in? %>
<%= render "comments/form", suggestion: @suggestion %>
<%= button_to "Upvote", suggestion_votes_path(@suggestion.id, vote: { :upvote => true }), :method => :post %>
<%= button_to "Downvote", suggestion_votes_path(@suggestion.id, vote: { :upvote => false }), :method => :post %>
<% end %>
<br>
<%= link_to "Home", root_url %>